DROP TABLE IF EXISTS PLAYER;
 
CREATE TABLE PLAYER (
    NAME VARCHAR(255) NOT NULL PRIMARY KEY);


DROP TABLE IF EXISTS PIT;
 
CREATE TABLE PIT (
    ID INTEGER NOT NULL PRIMARY KEY,  
    SEQ INTEGER NOT NULL,
    STONES  INTEGER NOT NULL,
    PLAYER_ID  VARCHAR(255) NOT NULL
);